- name: Installing NodeJS
  when: install_nodejs | bool
  become: true
  snap:
    name: node
    classic: yes
    channel: '{{ nodejs_lts }}'

- name: Installing npm "n" package
  when: install_nodejs | bool
  become: true
  npm:
    name: n
    global: yes
  environment: 
    PATH: "{{ ansible_env.PATH}}:/snap/bin"

- name: Download nvm installer
  when: install_nodejs | bool
  get_url: url=https://raw.githubusercontent.com/creationix/nvm/v0.31.3/install.sh dest=/tmp/nvm-installer.sh mode=0666

- name: Execute the nvm-installer.sh
  when: install_nodejs | bool
  shell: bash /tmp/nvm-installer.sh