- name: Install packages (vim ; nano ; git ; screen ; gcc ; make ; wget ; ssh)
  become: true
  apt:
    pkg:
      - curl 
      - vim
      - nano
      - git
      - screen
      - gcc
      - make
      - wget
      - ssh
      - snapd
      - snapd-xdg-open
      - software-properties-common
      - python3-pip
      - python3-setuptools

- name: Install Github3 module for python
  pip:
    name: github3.py
      
- name: Copy Vim Run Command file (.vimrc)
  template:
    src: ../templates/vimrc
    dest: /home/{{ ansible_user }}/.vimrc

- name: Copy Screen Run Command file (.screenrc)
  template:
    src: ../templates/screenrc
    dest: /home/{{ ansible_user }}/.screenrc

- name: Installing JetBrains PhpStorm
  become: true
  when: install_phpstorm | bool
  snap:
    name: phpstorm
    classic: yes

- name: Installing Microsoft Visual Studio Code
  become: true
  when: install_vscode | bool
  snap:
    name: code
    classic: yes
