- name: Install required system packages for Docker
  when: install_docker | bool
  become: true
  apt:
    pkg: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools

- name: Add Docker GPG apt Key
  when: install_docker | bool
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  when: install_docker | bool
  become: true
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ lsb_release }} stable'
    state: present

- name: Update apt and install docker-ce
  when: install_docker | bool
  become: true
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Add the user '{{ ansible_user }}' to the group 'docker'
  when: install_docker | bool
  become: true
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  