- apt_repository:
    repo: ppa:ondrej/php
    state: present
    filename: php
    mode: 0666
  become: true

- name: Install PHP 7.0 and some extensions
  become: true
  when: install_php70 | bool
  apt:
    pkg:
      - php7.0
      - php7.0-curl
      - php7.0-dom
      - php7.0-intl
      - php7.0-json
      - php7.0-ldap
      - php7.0-mbstring
      - php7.0-mysql
      - php7.0-pgsql
      - php7.0-soap
      - php7.0-xml
      - php7.0-zip

- name: Install PHP 7.1 and some extensions
  become: true
  when: install_php71 | bool
  apt:
    pkg:
      - php7.1
      - php7.1-curl
      - php7.1-dom
      - php7.1-intl
      - php7.1-json
      - php7.1-ldap
      - php7.1-mbstring
      - php7.1-mysql
      - php7.1-pgsql
      - php7.1-soap
      - php7.1-xml
      - php7.1-zip

- name: Install PHP 7.2 and some extensions
  become: true
  when: install_php72 | bool
  apt:
    pkg:
      - php7.2
      - php7.2-curl
      - php7.2-dom
      - php7.2-intl
      - php7.2-json
      - php7.2-ldap
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-pgsql
      - php7.2-soap
      - php7.2-xml
      - php7.2-zip

- name: Install PHP 7.3 and some extensions
  become: true
  when: install_php73 | bool
  apt:
    pkg:
      - php7.3
      - php7.3-curl
      - php7.3-dom
      - php7.3-intl
      - php7.3-json
      - php7.3-ldap
      - php7.3-mbstring
      - php7.3-mysql
      - php7.3-pgsql
      - php7.3-soap
      - php7.3-xml
      - php7.3-zip

- name: Install PHP 7.4 and some extensions
  become: true
  when: install_php74 | bool
  apt:
    pkg:
      - php7.4
      - php7.4-curl
      - php7.4-dom
      - php7.4-intl
      - php7.4-json
      - php7.4-ldap
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-pgsql
      - php7.4-soap
      - php7.4-xml
      - php7.4-zip

- name: Check if composer is installed
  command: ls -al /usr/local/bin
  register: composer_install_check

- name: Downloading Composer
  script: scripts/install-composer.sh
  when: composer_install_check.stdout.find('composer') == -1 and install_composer | bool

- name: Move Composer globally
  become: true
  command: mv composer.phar /usr/local/bin/composer
  when: composer_install_check.stdout.find('composer') == -1 and install_composer | bool
